QCanBusDevice: Consolidate createDeviceInfo()
This protected function is used from the CAN
plugins to create QCanBusDeviceInfo objects.

We want to add another parameter (plugin) to the
function in a follow-up commit, so let's first
remove unneeded overloads that were created during
Qt 5 times and only keep the very simple and the
all-embracing one.

While at it, remove the std::move calls as clang
gives performance warnings here:

socketcanbackend.cpp:149:23: error:
    moving a temporary object prevents copy elision
socketcanbackend.cpp:149:23: note:
    remove std::move call here

Change-Id: Ie83db3cd3a9d6b40b2da4a9ce736861a0ee8359f
Reviewed-by: Alex Blasche <alexander.blasche@qt.io>
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
(cherry picked from commit 98691947d1aa6fb3ab63c7b749bc6407fa01be8a)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>