Fix build with Clang 5.0: remove unused capture
qmodbusrtuserialmaster_p.h:356:68: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]

Change-Id: Ia53158e207a94bf49489fffd14c7903c7e4655cb
Reviewed-by: Alex Blasche <alexander.blasche@qt.io>